name = "soniclab-wareki"
main = "worker/index.ts"
compatibility_date = "2024-09-23"
assets = { directory = "./dist", binding = "ASSETS" }

routes = [
  { pattern = "wareki.soniclab.cc/*", zone_name = "soniclab.cc" }
]
