name = "soniclab-wareki"
compatibility_date = "2024-09-23"
main = "worker/index.ts"

routes = [
  { pattern = "soniclab.cc/wareki/*", zone_name = "soniclab.cc" },
  { pattern = "www.soniclab.cc/wareki/*", zone_name = "soniclab.cc" }
]
